### ISSUE TITLE
Navbar icons have underlines on hover (plus here's the code to fix it)

### ISSUE THREAD

**Issue by maximz** [recalapp/recal#120]
Currently, bootstrap defines: 

``` css
a:hover, a:focus {
color: #158cba;
text-decoration: underline;
}
```

We ought to remove the `text-decoration: underline;` line. Maybe also change the color to yellow on hover over the icon?

(Not sure where to add this CSS myself.)
